remote_theme: just-the-docs/just-the-docs

title: مستندات API
description: مستندات فارسی
lang: fa
markdown: kramdown

plugins:
  - jekyll-remote-theme

just_the_docs:
  css:
    - /assets/css/custom.css

color_scheme: dark
